### ISSUE TITLE
Problem with sliding vector comparision

### ISSUE THREAD

**Issue by smallelephant9516** [marcottelab/SLICEM#2]
Hi, guys,
Thanks for your sharing this script on GitHub, however, I meet some problem when running this script using your provided dataset. 
When it goes to sliding vector comparisons, it stops at there, how long should I wait normally for the whole process to be finish.

**Comment by EricVerbeke** [comment]
Hello,
Thank you for trying out SLICEM. The vector comparison step is the slowest step in the program. For the provided dataset it can take a few hours to complete. If you cancelled the job part way through, you should still be able to print out the scores it has calculated to confirm it was running.

For running on your own data, I would first recommend binning your class averages to <100pixels to help save time. I hope to implement a massively sped up version of this code in the future. Please feel free to contact me if there are any more issues.

- Eric

**Comment by EricVerbeke** [comment]
A new version with multiprocessing and command line arguments has been added. This should help speed things up while I'm working on further improvements! 

On the example data I provided, using Euclidean distance:
1 cpu takes ~ 180 min
8 cpu takes ~ 50 min
50 cpu takes ~ 6 min

Hope that helps,
- Eric
